VERSAO_ATUAL = "1.7.2" # <--- Mudar sempre ao Atualizar

# C.entena D.ezena U.nidade
# C = REFORMULAÇÃO TOTAL DO APLICATIVO (INCLUI INTERFACE, METODO DE USO, NOVOS MODOS, ALGO INOVADOR EM SI)
# D = REFORMULAÇÃO PARCIAL DO APLICATIVO (MODO DE USO, ALGO QUE VÁ INTERFERIR NA DINÂMICA DO USUÁRIO)
# U = CORREÇÃO DE BUGS OU LANÇAMENTOS SIMPLES (NEM PRECISO DIZER :D)